In [5]:
from benchmark import medir, paso_nbody, crear_particulas,simulacion_nbody
from benchmark import benchmark_cpu
from benchmark import benchmark_memoria
from benchmark import benchmark_disco

import pandas as pd


def trabajo_falso():
    return sum(i * i for i in range(1_000_000))

medir(trabajo_falso)
# Esperás algo como:
# {'tiempo_s': 0.045..., 'memoria_delta_mb': 0.0..., 'resultado': ...}

{'tiempo_s': 0.04513595800381154,
 'memoria_delta_mb': 0.015625,
 'resultado': 333332833333500000}

In [3]:
resultado = medir(simulacion_nbody, 500)
print(f"Tiempo:    {resultado['tiempo_s']:.4f} s")
print(f"Memoria:   {resultado['memoria_delta_mb']:.2f} MB")
print(f"Partículas devueltas: {len(resultado['resultado'])}")

Tiempo:    0.0478 s
Memoria:   0.00 MB
Partículas devueltas: 500

In [4]:
registros_cpu = benchmark_cpu()
df_cpu = pd.DataFrame(registros_cpu)
df_cpu

[CPU] N = 1500 partículas (1,124,250 pares de cálculos)
  rep 1/8: 0.248 s
  rep 2/8: 0.256 s
  rep 3/8: 0.256 s
  rep 4/8: 0.241 s
  rep 5/8: 0.256 s
  rep 6/8: 0.236 s
  rep 7/8: 0.257 s
  rep 8/8: 0.256 s

[CPU] N = 2000 partículas (1,999,000 pares de cálculos)
  rep 1/8: 0.415 s
  rep 2/8: 0.430 s
  rep 3/8: 0.429 s
  rep 4/8: 0.428 s
  rep 5/8: 0.433 s
  rep 6/8: 0.426 s
  rep 7/8: 0.435 s
  rep 8/8: 0.430 s

[CPU] N = 2800 partículas (3,918,600 pares de cálculos)
  rep 1/8: 0.806 s
  rep 2/8: 0.806 s
  rep 3/8: 0.831 s
  rep 4/8: 0.814 s
  rep 5/8: 0.827 s
  rep 6/8: 0.824 s
  rep 7/8: 0.825 s
  rep 8/8: 0.813 s

[CPU] N = 4000 partículas (7,998,000 pares de cálculos)
  rep 1/8: 1.663 s
  rep 2/8: 1.644 s
  rep 3/8: 1.632 s
  rep 4/8: 1.670 s
  rep 5/8: 1.636 s
  rep 6/8: 1.640 s
  rep 7/8: 1.642 s
  rep 8/8: 1.640 s

[CPU] N = 5500 partículas (15,122,250 pares de cálculos)
  rep 1/8: 3.105 s
  rep 2/8: 3.095 s
  rep 3/8: 3.104 s
  rep 4/8: 3.110 s
  rep 5/8: 3.091 s
  rep 6/8: 3.094 s
  rep 7/8: 3.102 s
  rep 8/8: 3.115 s

,escenario,tamano_n,tamano_pares,repeticion,tiempo_s,memoria_delta_mb,throughput_pares_s
0,cpu_nbody,1500,1124250,1,0.247546,0.000000,4.541576e+06
1,cpu_nbody,1500,1124250,2,0.256186,0.015625,4.388414e+06
2,cpu_nbody,1500,1124250,3,0.255555,0.000000,4.399250e+06
3,cpu_nbody,1500,1124250,4,0.241179,0.000000,4.661482e+06
4,cpu_nbody,1500,1124250,5,0.256206,0.000000,4.388075e+06
5,cpu_nbody,1500,1124250,6,0.236036,0.000000,4.763047e+06
6,cpu_nbody,1500,1124250,7,0.256679,0.000000,4.379988e+06
7,cpu_nbody,1500,1124250,8,0.255602,0.000000,4.398435e+06
8,cpu_nbody,2000,1999000,1,0.415088,0.109375,4.815851e+06
9,cpu_nbody,2000,1999000,2,0.430325,0.125000,4.645327e+06
10,cpu_nbody,2000,1999000,3,0.429240,0.000000,4.657074e+06
11,cpu_nbody,2000,1999000,4,0.428028,0.000000,4.670260e+06
12,cpu_nbody,2000,1999000,5,0.432943,0.000000,4.617231e+06
13,cpu_nbody,2000,1999000,6,0.426487,0.000000,4.687135e+06
14,cpu_nbody,2000,1999000,7,0.435411,0.000000,4.591062e+06
15,cpu_nbody,2000,1999000,8,0.430180,0.000000,4.646895e+06
16,cpu_nbody,2800,3918600,1,0.805650,0.296875,4.863901e+06
17,cpu_nbody,2800,3918600,2,0.805529,0.281250,4.864627e+06
18,cpu_nbody,2800,3918600,3,0.831152,0.000000,4.714661e+06
19,cpu_nbody,2800,3918600,4,0.814314,0.000000,4.812149e+06
20,cpu_nbody,2800,3918600,5,0.826572,0.000000,4.740787e+06
21,cpu_nbody,2800,3918600,6,0.824424,0.000000,4.753138e+06
22,cpu_nbody,2800,3918600,7,0.824851,0.000000,4.750676e+06
23,cpu_nbody,2800,3918600,8,0.812597,0.000000,4.822314e+06
24,cpu_nbody,4000,7998000,1,1.663042,0.562500,4.809258e+06
25,cpu_nbody,4000,7998000,2,1.644186,0.390625,4.864414e+06
26,cpu_nbody,4000,7998000,3,1.632223,0.000000,4.900065e+06
27,cpu_nbody,4000,7998000,4,1.670380,0.000000,4.788131e+06
28,cpu_nbody,4000,7998000,5,1.635501,0.000000,4.890244e+06
29,cpu_nbody,4000,7998000,6,1.639699,0.000000,4.877724e+06
30,cpu_nbody,4000,7998000,7,1.642258,0.000000,4.870123e+06
31,cpu_nbody,4000,7998000,8,1.639913,0.000000,4.877089e+06
32,cpu_nbody,5500,15122250,1,3.105144,0.703125,4.870064e+06
33,cpu_nbody,5500,15122250,2,3.095155,0.500000,4.885781e+06
34,cpu_nbody,5500,15122250,3,3.104074,0.000000,4.871742e+06
35,cpu_nbody,5500,15122250,4,3.110149,0.000000,4.862228e+06
36,cpu_nbody,5500,15122250,5,3.090866,0.000000,4.892561e+06
37,cpu_nbody,5500,15122250,6,3.093765,0.000000,4.887976e+06
38,cpu_nbody,5500,15122250,7,3.102246,0.000000,4.874614e+06
39,cpu_nbody,5500,15122250,8,3.114583,0.000000,4.855305e+06

In [2]:
# Celda nueva
registros_mem = benchmark_memoria()
df_mem = pd.DataFrame(registros_mem)
df_mem

[MEM] Matriz 500×500  (250,000 elementos, 1.9 MB)
  Acceso por filas (secuencial en memoria):
    rep 1/8: 0.0007 s
    rep 2/8: 0.0018 s
    rep 3/8: 0.0008 s
    rep 4/8: 0.0008 s
    rep 5/8: 0.0006 s
    rep 6/8: 0.0019 s
    rep 7/8: 0.0019 s
    rep 8/8: 0.0011 s
  Acceso por columnas (con saltos en memoria):
    rep 1/8: 0.0027 s
    rep 2/8: 0.0027 s
    rep 3/8: 0.0016 s
    rep 4/8: 0.0020 s
    rep 5/8: 0.0027 s
    rep 6/8: 0.0016 s
    rep 7/8: 0.0027 s
    rep 8/8: 0.0027 s

[MEM] Matriz 1200×1200  (1,440,000 elementos, 11.0 MB)
  Acceso por filas (secuencial en memoria):
    rep 1/8: 0.0011 s
    rep 2/8: 0.0047 s
    rep 3/8: 0.0046 s
    rep 4/8: 0.0032 s
    rep 5/8: 0.0031 s
    rep 6/8: 0.0056 s
    rep 7/8: 0.0026 s
    rep 8/8: 0.0036 s
  Acceso por columnas (con saltos en memoria):
    rep 1/8: 0.0069 s
    rep 2/8: 0.0062 s
    rep 3/8: 0.0079 s
    rep 4/8: 0.0055 s
    rep 5/8: 0.0050 s
    rep 6/8: 0.0052 s
    rep 7/8: 0.0064 s
    rep 8/8: 0.0070 s

[MEM] Matriz 2800×2800  (7,840,000 elementos, 59.8 MB)
  Acceso por filas (secuencial en memoria):
    rep 1/8: 0.0042 s
    rep 2/8: 0.0168 s
    rep 3/8: 0.0105 s
    rep 4/8: 0.0091 s
    rep 5/8: 0.0089 s
    rep 6/8: 0.0100 s
    rep 7/8: 0.0102 s
    rep 8/8: 0.0105 s
  Acceso por columnas (con saltos en memoria):
    rep 1/8: 0.0295 s
    rep 2/8: 0.0282 s
    rep 3/8: 0.0252 s
    rep 4/8: 0.0205 s
    rep 5/8: 0.0226 s
    rep 6/8: 0.0294 s
    rep 7/8: 0.0272 s
    rep 8/8: 0.0161 s

[MEM] Matriz 6000×6000  (36,000,000 elementos, 274.7 MB)
  Acceso por filas (secuencial en memoria):
    rep 1/8: 0.0313 s
    rep 2/8: 0.0333 s
    rep 3/8: 0.0305 s
    rep 4/8: 0.0290 s
    rep 5/8: 0.0245 s
    rep 6/8: 0.0274 s
    rep 7/8: 0.0283 s
    rep 8/8: 0.0272 s
  Acceso por columnas (con saltos en memoria):
    rep 1/8: 0.0902 s
    rep 2/8: 0.0864 s
    rep 3/8: 0.0954 s
    rep 4/8: 0.0926 s
    rep 5/8: 0.0996 s
    rep 6/8: 0.0826 s
    rep 7/8: 0.0922 s
    rep 8/8: 0.0911 s

[MEM] Matriz 11000×11000  (121,000,000 elementos, 923.2 MB)
  Acceso por filas (secuencial en memoria):
    rep 1/8: 0.0973 s
    rep 2/8: 0.0488 s
    rep 3/8: 0.0551 s
    rep 4/8: 0.0381 s
    rep 5/8: 0.0413 s
    rep 6/8: 0.0540 s
    rep 7/8: 0.0560 s
    rep 8/8: 0.0508 s
  Acceso por columnas (con saltos en memoria):
    rep 1/8: 0.2157 s
    rep 2/8: 0.2097 s
    rep 3/8: 0.2150 s
    rep 4/8: 0.2139 s
    rep 5/8: 0.2166 s
    rep 6/8: 0.2040 s
    rep 7/8: 0.1990 s
    rep 8/8: 0.2117 s

,escenario,tamano_n,tamano_elementos,tamano_mb,repeticion,tiempo_s,memoria_delta_mb,throughput_mb_s
0,memoria_filas,500,250000,1.907349,1,0.000665,0.0,2868.909556
1,memoria_filas,500,250000,1.907349,2,0.001845,0.0,1033.770325
2,memoria_filas,500,250000,1.907349,3,0.000838,0.0,2275.618846
3,memoria_filas,500,250000,1.907349,4,0.000776,0.0,2457.264829
4,memoria_filas,500,250000,1.907349,5,0.000574,0.0,3323.387579
...,...,...,...,...,...,...,...,...
75,memoria_columnas,11000,121000000,923.156738,4,0.213851,0.0,4316.826391
76,memoria_columnas,11000,121000000,923.156738,5,0.216582,0.0,4262.387365
77,memoria_columnas,11000,121000000,923.156738,6,0.203967,0.0,4526.012141
78,memoria_columnas,11000,121000000,923.156738,7,0.198992,0.0,4639.174805
79,memoria_columnas,11000,121000000,923.156738,8,0.211720,0.0,4360.273475

In [3]:
resumen_mem = df_mem.groupby(['escenario', 'tamano_n']).agg(
    n_reps=('tiempo_s', 'count'),
    tiempo_mean=('tiempo_s', 'mean'),
    tiempo_std=('tiempo_s', 'std'),
    throughput_mean_mb_s=('throughput_mb_s', 'mean'),
    throughput_std=('throughput_mb_s', 'std'),
).reset_index()
resumen_mem

,escenario,tamano_n,n_reps,tiempo_mean,tiempo_std,throughput_mean_mb_s,throughput_std
0,memoria_columnas,500,8,0.002330,0.000513,861.631615,224.519837
1,memoria_columnas,1200,8,0.006243,0.001016,1800.932645,291.299194
2,memoria_columnas,2800,8,0.024837,0.004789,2505.133426,583.249273
3,memoria_columnas,6000,8,0.091261,0.005219,3018.325315,174.922683
4,memoria_columnas,11000,8,0.210691,0.006241,4385.013416,133.390372
5,memoria_filas,500,8,0.001205,0.000584,1954.061627,910.521595
6,memoria_filas,1200,8,0.003563,0.001394,3824.125053,2456.895092
7,memoria_filas,2800,8,0.010027,0.003435,6796.489307,3180.476699
8,memoria_filas,6000,8,0.028931,0.002739,9569.047066,917.286539
9,memoria_filas,11000,8,0.055175,0.018225,17939.989930,4411.170604

In [6]:
registros_disco = benchmark_disco()
df_disco = pd.DataFrame(registros_disco)
df_disco

[DISCO-BINARIO] 200 MB (26,214,400 float64)
  Escritura:
    rep 1/8: 0.033 s
    rep 2/8: 0.052 s
    rep 3/8: 0.049 s
    rep 4/8: 0.053 s
    rep 5/8: 0.051 s
    rep 6/8: 0.050 s
    rep 7/8: 0.038 s
    rep 8/8: 0.040 s
  Lectura:
    rep 1/8: 0.057 s
    rep 2/8: 0.040 s
    rep 3/8: 0.042 s
    rep 4/8: 0.050 s
    rep 5/8: 0.044 s
    rep 6/8: 0.044 s
    rep 7/8: 0.036 s
    rep 8/8: 0.040 s

[DISCO-BINARIO] 400 MB (52,428,800 float64)
  Escritura:
    rep 1/8: 0.076 s
    rep 2/8: 0.089 s
    rep 3/8: 0.089 s
    rep 4/8: 0.093 s
    rep 5/8: 0.086 s
    rep 6/8: 0.092 s
    rep 7/8: 0.088 s
    rep 8/8: 0.093 s
  Lectura:
    rep 1/8: 0.145 s
    rep 2/8: 0.164 s
    rep 3/8: 0.087 s
    rep 4/8: 0.097 s
    rep 5/8: 0.069 s
    rep 6/8: 0.068 s
    rep 7/8: 0.058 s
    rep 8/8: 0.057 s

[DISCO-BINARIO] 750 MB (98,304,000 float64)
  Escritura:
    rep 1/8: 0.232 s
    rep 2/8: 0.227 s
    rep 3/8: 0.234 s
    rep 4/8: 0.252 s
    rep 5/8: 0.221 s
    rep 6/8: 0.228 s
    rep 7/8: 0.239 s
    rep 8/8: 0.244 s
  Lectura:
    rep 1/8: 0.131 s
    rep 2/8: 0.149 s
    rep 3/8: 0.086 s
    rep 4/8: 0.108 s
    rep 5/8: 0.078 s
    rep 6/8: 0.094 s
    rep 7/8: 0.097 s
    rep 8/8: 0.078 s

[DISCO-BINARIO] 1400 MB (183,500,800 float64)
  Escritura:
    rep 1/8: 0.774 s
    rep 2/8: 0.569 s
    rep 3/8: 0.575 s
    rep 4/8: 0.553 s
    rep 5/8: 0.559 s
    rep 6/8: 0.611 s
    rep 7/8: 0.635 s
    rep 8/8: 0.555 s
  Lectura:
    rep 1/8: 0.494 s
    rep 2/8: 0.303 s
    rep 3/8: 0.301 s
    rep 4/8: 0.459 s
    rep 5/8: 0.217 s
    rep 6/8: 0.213 s
    rep 7/8: 0.174 s
    rep 8/8: 0.154 s

[DISCO-BINARIO] 2500 MB (327,680,000 float64)
  Escritura:
    rep 1/8: 1.387 s
    rep 2/8: 1.122 s
    rep 3/8: 1.137 s
    rep 4/8: 1.121 s
    rep 5/8: 1.108 s
    rep 6/8: 1.125 s
    rep 7/8: 1.142 s
    rep 8/8: 1.114 s
  Lectura:
    rep 1/8: 0.584 s
    rep 2/8: 1.350 s
    rep 3/8: 1.044 s
    rep 4/8: 0.853 s
    rep 5/8: 0.267 s
    rep 6/8: 0.584 s
    rep 7/8: 0.423 s
    rep 8/8: 0.354 s

[DISCO-CSV] 200 MB (26,214,400 float64)
  Escritura:
    rep 1/8: 15.685 s
    rep 2/8: 15.777 s
    rep 3/8: 15.869 s
    rep 4/8: 15.916 s
    rep 5/8: 16.016 s
    rep 6/8: 15.892 s
    rep 7/8: 15.956 s
    rep 8/8: 15.991 s
  Lectura:
    rep 1/8: 3.689 s
    rep 2/8: 3.586 s
    rep 3/8: 3.576 s
    rep 4/8: 3.583 s
    rep 5/8: 3.610 s
    rep 6/8: 3.605 s
    rep 7/8: 3.613 s
    rep 8/8: 3.635 s

[DISCO-CSV] 400 MB (52,428,800 float64)
  Escritura:
    rep 1/8: 31.926 s
    rep 2/8: 32.041 s
    rep 3/8: 32.178 s
    rep 4/8: 32.169 s
    rep 5/8: 32.609 s
    rep 6/8: 32.050 s
    rep 7/8: 32.160 s
    rep 8/8: 32.245 s
  Lectura:
    rep 1/8: 7.254 s
    rep 2/8: 7.213 s
    rep 3/8: 7.158 s
    rep 4/8: 7.149 s
    rep 5/8: 7.167 s
    rep 6/8: 7.149 s
    rep 7/8: 7.127 s
    rep 8/8: 7.165 s

,escenario,tamano_mb,repeticion,tiempo_s,memoria_delta_mb,throughput_mb_s
0,disco_escritura_binario,200,1,0.033362,0.000000,5994.821972
1,disco_escritura_binario,200,2,0.051517,0.000000,3882.179124
2,disco_escritura_binario,200,3,0.049228,0.000000,4062.745693
3,disco_escritura_binario,200,4,0.053149,0.000000,3763.023590
4,disco_escritura_binario,200,5,0.050638,0.000000,3949.586764
...,...,...,...,...,...,...
107,disco_lectura_csv,400,4,7.149446,400.000000,55.948392
108,disco_lectura_csv,400,5,7.167103,-404.500000,55.810559
109,disco_lectura_csv,400,6,7.149276,400.015625,55.949724
110,disco_lectura_csv,400,7,7.127028,400.015625,56.124376
111,disco_lectura_csv,400,8,7.164995,-799.953125,55.826973

In [7]:
resumen_disco = df_disco.groupby(['escenario', 'tamano_mb']).agg(
    n_reps=('tiempo_s', 'count'),
    tiempo_mean=('tiempo_s', 'mean'),
    tiempo_std=('tiempo_s', 'std'),
    throughput_mean_mb_s=('throughput_mb_s', 'mean'),
    throughput_std=('throughput_mb_s', 'std'),
).reset_index()
resumen_disco

,escenario,tamano_mb,n_reps,tiempo_mean,tiempo_std,throughput_mean_mb_s,throughput_std
0,disco_escritura_binario,200,8,0.045736,0.007491,4490.992187,828.124301
1,disco_escritura_binario,400,8,0.088108,0.005521,4557.165913,315.699763
2,disco_escritura_binario,750,8,0.234648,0.010016,3201.305883,134.953835
3,disco_escritura_binario,1400,8,0.603868,0.074522,2344.781557,245.517279
4,disco_escritura_binario,2500,8,1.156869,0.093559,2171.662681,150.666232
5,disco_escritura_csv,200,8,15.887653,0.110931,12.588931,0.088300
6,disco_escritura_csv,400,8,32.172150,0.203132,12.433545,0.077970
7,disco_lectura_binario,200,8,0.044151,0.006575,4611.023926,629.702220
8,disco_lectura_binario,400,8,0.093041,0.040573,4943.053050,1753.624492
9,disco_lectura_binario,750,8,0.102650,0.025565,7668.456499,1689.702549
10,disco_lectura_binario,1400,8,0.289345,0.127449,5663.983400,2257.949348
11,disco_lectura_binario,2500,8,0.682227,0.372548,4759.795934,2555.011254
12,disco_lectura_csv,200,8,3.612087,0.036568,55.374558,0.554523
13,disco_lectura_csv,400,8,7.172842,0.041001,55.767491,0.316999